version: '2.1'
services:
  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch
    networks:
      - elasticnet
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.17.18
    container_name: kibana  
    ports:
      - "5601:5601"    
    networks:
      - elasticnet

volumes:
  data01:
    driver: local

networks:
  elasticnet:
    external: true
      